### ISSUE TITLE
More steps than 3...

### ISSUE THREAD

**Issue by vladotesanovic** [ngzhian/multi-step-modal#3]
You have one bug, if you try to add more steps than 3, progress bar will behave weird.

Problem is with variable total_num_steps 
var total_num_steps = $buttons.length; // line 9 in multi-step-modal.js

Number of buttons is not good indicator of total_num_steps, i switch this to:

var total_num_steps = $modal.find('.modal-title').length;  // and everything work properly.

**Comment by ngzhian** [comment]
Thanks for the report, the length is calculate based on `$modal.find('button.step');`, so only `button` with a `step` class will be considered as a step. Maybe you didn't add a `button` with `step` class, that's why the behavior was weird with more than 3 steps?

**Comment by vladotesanovic** [comment]
I added, but imagine: if you have 5 steps you will need 5 continue buttons and 4 back buttons... that is 9 buttons with class step...

I solve it like i mention above, and that work for me.

**Comment by vladotesanovic** [comment]
Thank you for great and usable code, anyway. :)

**Comment by ngzhian** [comment]
I see, great point. I think in my code what I did was all the Back buttons had this code

``` html
<button data-step="2" class="btn btn-primary back step-2 pull-right" type="button">Back</button>
```

They do not have the class `step` so they are not counted in the number of steps of the modal!
Other than that, I think your solution works really well, but doesn't work if I do not have a `.modal-title`, which is the case in my use case! :P 

Thanks! Apologies this code hasn't been updated or document, it worked well for my use case and I have left it as such heh. Glad it has been of use to you :)

**Comment by monomadic** [comment]
Why not just count the amount of .step classes there are instead of worrying about buttons at all? Since the buttons have to be hooked up manually and have little to do with the amount of steps there are, it makes little sense to count them and could easily introduce implementation errors.

In my own implementation I don't use buttons at all and changed the enumerator to work this way. It's far cleaner.

**Comment by ngzhian** [comment]
@robsaunders the reason is because I use `$('.step')` as the selector to reset the entire modal (hide everything) upon initialization and before every step. Each modal header and modal body has the class 'step', so taking `$('.step').length` will give me the wrong number of steps.
That said, this code worked well enough for my use case, and this project is clearly not maintained and is just open sourced for people who happen to need this really simple code.

**Comment by amarms** [comment]
@robsaunders @ngzhian Just changing $('.step') to $('.modal-body.step') should do the job as the number of steps 'pages' should be the final number of steps.

**Comment by ngzhian** [comment]
@amarms thanks for your suggestion, I haven't been using this library for a while, if you would like to submit this as a pull request it will be very welcomed! :)
